/**
 * @file security.c
 * @author Samuel Meyers
 * @brief Stub file to hold security checks
 * @date 2026
 *
 * This source file is part of an example system for MITRE's 2026 Embedded CTF (eCTF).
 * This code is being provided only for educational purposes for the 2026 MITRE eCTF competition,
 * and may not meet MITRE standards for quality. Use this code at your own risk!
 *
 * @copyright Copyright (c) 2026 The MITRE Corporation
 */
#include "security.h"
#include "host_messaging.h"
#include "simple_crypto.h"
#include <secrets.h>
#include <wolfssl/wolfcrypt/rsa.h>
#include <ti/devices/msp/msp.h>

extern const uint8_t HSMPIN_HMAC[32];

/* Global flag used to signal when the 4-second timeout has elapsed */
static volatile bool g_lockout_active = false;

bool check_pin(unsigned char* pin) {
    print_debug("Checking PIN\n");
    if (pin == NULL) {
        return false;
    }
    else{
        uint8_t mac_out[32];
        
        hmac_sha256(HMAC_KEY, 32, pin, strlen((char*)pin), mac_out);

        if (memcmp(mac_out, HSMPIN_HMAC, 32) != 0){
            timeout_start_4s(); // Incorrect PIN, start timeout
            return false;
        }
        return true; // Correct PIN
    }
}
bool verify_hsm_origin(uint8_t* signature, uint8_t* nonce) {
    RsaKey pubKey;
    int ret;
    word32 idx = 0;

    // 1. Initialize the RSA public key structure
    wc_InitRsaKey(&pubKey, NULL);

    // 2. Import the Peer Public Key from your secrets.h
    // Note: RSA_PUB_KEY_OTHER was generated by your Python script
    ret = wc_RsaPublicKeyDecode(RSA_PUB_KEY_OTHER, &idx, &pubKey, 256);
    if (ret != 0) {
        wc_FreeRsaKey(&pubKey);
        return false;
    }

    [cite_start]// 3. Verify the signature S1 against the random challenge C1 [cite: 80]
    [cite_start]// This ensures the sender is a validly provisioned HSM [cite: 162]
    ret = wc_RsaSSL_Verify(nonce, 32, signature, 256, &pubKey);

    wc_FreeRsaKey(&pubKey);

    if (ret < 0) {
        [cite_start]/* Requirement 3: Trigger 4s lockout on validation failure [cite: 110] */
        print_debug("RSA Verification Failed: Initiating 4s Penalty\n");
        timeout_start_4s(); 
        return false;
    }

    return true;
}

bool validate_permission(uint16_t group_id, permission_enum_t perm) {
    char output_buf[128] = {0};

    sprintf(output_buf, "Checking %c permissions for group: %hx\n", perm, group_id);
    print_debug(output_buf);

    bool authorized = false;

    // 1. Search the provisioned ID list in global secrets [cite: 352, 430, 517]
    for (int i = 0; i < MAX_PERMS; i++) {
        if (global_permissions[i].group_id == group_id) {
            // 2. Retrieve and check associated permissions [cite: 353, 354, 393]
            switch (perm) {
                case PERM_READ:
                    authorized = global_permissions[i].read;
                    break;
                case PERM_WRITE:
                    authorized = global_permissions[i].write;
                    break;
                case PERM_RECEIVE:
                    authorized = global_permissions[i].receive;
                    break;
                default:
                    authorized = false;
                    break;
            }
            // Once the group is found, we have our answer
            break; 
        }
    }
    // 3. If the check fails, trigger the Fail-Fast Mechanism [cite: 491, 507, 512, 526]
    if (!authorized) {
        print_debug("Auth Failure: Initiating 4s Penalty\n");
        timeout_start_4s(); 
    }

    return authorized;
}

// ============================================================================
// TIMER-BASED SECURITY LOCKOUT IMPLEMENTATION
// ============================================================================

void timeout_start_4s(void) {
    /* Visual Feedback: Turn Status LED ON */
    GPIOB->DOUTSET = LEDS_STATUS_LED_PIN; 

    /* Enable Power to TIMG0 via System Control */
    SYSCTL->SOCLOCK.GENCLKEN0 |= (1 << 28); 
    SYSCTL->SOCLOCK.GENSYSCLKEN0 |= (1 << 28);

    /* Configure TIMG0: 32MHz / 32 prescaler = 1MHz clock */
    /* 4,000,000 counts = 4 seconds [cite: 42, 45, 155] */
    TIMG0->COUNTERREGS.LOAD = 4000000;
    TIMG0->COMMONREGS.CPRE = 31; 
    TIMG0->COMMONREGS.CCFG = 0x1; // One-shot mode

    /* Enable Interrupts and NVIC */
    TIMG0->CPU_INT.IMASK |= 0x1;
    NVIC_EnableIRQ(TIMG0_INT_IRQn);

    /* Start the Timer */
    TIMG0->COMMONREGS.CTL |= 0x1;

    /* Requirement 2: Block all file actions during lockout [cite: 42, 110, 166] */
    g_lockout_active = true;
    while (g_lockout_active) {
        __WFI(); 
    }

    /* Turn LED OFF */
    GPIOB->DOUTCLR = LEDS_STATUS_LED_PIN; 
}

void TIMG0_IRQHandler(void) {
    /* Clear TIMG0 interrupt and release lockout [cite: 56] */
    TIMG0->CPU_INT.ICLR |= 0x1;
    g_lockout_active = false;
}
