/**
 * @file security.c
 * @author Samuel Meyers
 * @brief Stub file to hold security checks
 * @date 2026
 *
 * This source file is part of an example system for MITRE's 2026 Embedded CTF (eCTF).
 * This code is being provided only for educational purposes for the 2026 MITRE eCTF competition,
 * and may not meet MITRE standards for quality. Use this code at your own risk!
 *
 * @copyright Copyright (c) 2026 The MITRE Corporation
 */
#include "security.h"
#include "rng.h"
#include "host_messaging.h"
#include "simple_crypto.h"
#include <secrets.h>
#include <wolfssl/wolfcrypt/aes.h>
#include <ti/devices/msp/msp.h>
#include <wolfssl/wolfcrypt/rsa.h>

extern const uint8_t HSMPIN_HMAC[32];

/* Global flag used to signal when the 4-second timeout has elapsed */
static volatile bool timeout_elapsed = false;

bool check_pin(unsigned char* pin) {
    print_debug("Checking PIN\n");
    if (pin == NULL) {
        return false;
    }
    else{
        uint8_t mac_out[32];
        
        hmac_sha256(HMAC_KEY, 32, pin, strlen((char*)pin), mac_out);

        if (memcmp(mac_out, HSMPIN_HMAC, 32) != 0){
            timeout_start_4s(); // Incorrect PIN, start timeout
            return false;
        }
        return true; // Correct PIN
    }
}
bool verify_hsm_origin(uint8_t* signature, uint8_t* nonce) {
    RsaKey pubKey;
    int ret;
    word32 idx = 0;

    // 1. Initialize the RSA public key structure
    wc_InitRsaKey(&pubKey, NULL);

    // 2. Import the Peer Public Key from your secrets.h
    // Note: RSA_PUB_KEY_OTHER was generated by your Python script
    ret = wc_RsaPublicKeyDecode(RSA_PUB_KEY_OTHER, &idx, &pubKey, 256);
    if (ret != 0) {
        wc_FreeRsaKey(&pubKey);
        return false;
    }

    ret = wc_RsaSSL_Verify(nonce, 32, signature, 256, &pubKey);

    wc_FreeRsaKey(&pubKey);

    if (ret < 0) {
        print_debug("RSA Verification Failed: Initiating 4s Penalty\n");
        timeout_start_4s(); 
        return false;
    }

    return true;
}

bool validate_permission(uint16_t group_id, permission_enum_t perm) {
    char output_buf[128] = {0};

    sprintf(output_buf, "Checking %c permissions for group: %hx\n", perm, group_id);
    print_debug(output_buf);

    bool authorized = false;

    // 1. Search the provisioned ID list in global secrets [cite: 352, 430, 517]
    for (int i = 0; i < MAX_PERMS; i++) {
        if (global_permissions[i].group_id == group_id) {
            // 2. Retrieve and check associated permissions [cite: 353, 354, 393]
            switch (perm) {
                case PERM_READ:
                    authorized = global_permissions[i].read;
                    break;
                case PERM_WRITE:
                    authorized = global_permissions[i].write;
                    break;
                case PERM_RECEIVE:
                    authorized = global_permissions[i].receive;
                    break;
                default:
                    authorized = false;
                    break;
            }
            // Once the group is found, we have our answer
            break; 
        }
    }
    // 3. If the check fails, trigger the Fail-Fast Mechanism [cite: 491, 507, 512, 526]
    if (!authorized) {
        print_debug("Auth Failure: Initiating 4s Penalty\n");
        timeout_start_4s(); 
    }

    return authorized;
}

void timeout_start_4s(void) {
    /* 1. Calculate Jitter */
    uint32_t jitter = trng_get_word() % 500000; 
    uint32_t total_load = 4000000 + jitter; 

    /* Step 2: Reset and Enable TIMG0 Clock using Direct Addressing */
    /* SYSCTL Base: 0x400AF000 */
    /* GENSYSRST (Peripheral Reset Group 0) Offset: 0x00 */
    /* GENSYSCLKEN (Peripheral Clock Group 0) Offset: 0x20 */
    
    // Assert reset for TIMG0 (Bit 28)
    *((volatile uint32_t *)(0x400AF000 + 0x00)) |= (1 << 28); 
    
    // Enable clock gate for TIMG0 (Bit 28)
    *((volatile uint32_t *)(0x400AF000 + 0x20)) |= (1 << 28); 
    
    /* Step 3: Configure TIMG0 registers */
    // Using 'CPS' as we verified earlier in your SDK check
    TIMG0->COUNTERREGS.LOAD = total_load; 
    TIMG0->COMMONREGS.CPS   = 31; // Prescaler for 1MHz
    
    /* 4. Start Timer and Interrupts */
    TIMG0->COMMONREGS.GCTL |= 0x1;
    TIMG0->CPU_INT.IMASK   |= (1 << 0);
    NVIC->ISER[0] |= (1 << TIMG0_INT_IRQn);
    
    timeout_elapsed = false;
    while (!timeout_elapsed) {
        __WFI(); 
    }
}
